In [1]:
import numpy as np
import pandas as pd

In [3]:
# two matrics
array1 = np.array([[2, 5, 1],[9, -2, 6]])
array2 = np.array([[5,-2],[9, 2],[6, -7]])
print(array1)
print(array2)

[[ 2  5  1]
 [ 9 -2  6]]
[[ 5 -2]
 [ 9  2]
 [ 6 -7]]


In [5]:
#randomly initialize array
array = np.random.rand(3, 4)
print(array)

[[0.22526337 0.33573992 0.07215334 0.38489042]
 [0.91225227 0.97949    0.11643796 0.78367474]
 [0.89757721 0.13389353 0.39204777 0.15751003]]


In [6]:
# perform matrix multiplication
multiplication = np.dot(array1, array2)
print(multiplication)

[[ 61  -1]
 [ 63 -64]]


In [7]:
# perform element wise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res) 

[[61, -1], [63, -64]]


In [8]:
# mean of first matrix
mean = np.mean(array1)
print(mean)

3.5


In [9]:
main_data = pd.read_csv("mtcars.csv")

In [10]:
del main_data['model']
# meancenter
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())

        mpg     cyl        disp       hp      drat       wt     qsec      vs  \
0  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.59725 -1.38875 -0.4375   
1  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.34225 -0.82875 -0.4375   
2  2.709375 -2.1875 -122.721875 -53.6875  0.253437 -0.89725  0.76125  0.5625   
3  1.309375 -0.1875   27.278125 -36.6875 -0.516563 -0.00225  1.59125  0.5625   
4 -1.390625  1.8125  129.278125  28.3125 -0.446563  0.22275 -0.82875 -0.4375   

        am    gear    carb  
0  0.59375  0.3125  1.1875  
1  0.59375  0.3125  1.1875  
2  0.59375  0.3125 -1.8125  
3 -0.40625 -0.6875 -1.8125  
4 -0.40625 -0.6875 -0.8125  
