In [3]:
# Import Numpy & PyTorch

import numpy as np
import torch
import torch.nn as nn

In [4]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [5]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [6]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [19]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
next(iter(train_dl))

[tensor([[ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [102.,  43.,  37.],
         [102.,  43.,  37.],
         [ 87., 134.,  58.]]), tensor([[103., 119.],
         [ 56.,  70.],
         [ 22.,  37.],
         [ 22.,  37.],
         [119., 133.]])]

In [20]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3404, -0.5564,  0.2166],
        [ 0.0326, -0.4421,  0.0963]], requires_grad=True)
Parameter containing:
tensor([0.0739, 0.0833], requires_grad=True)


In [21]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [22]:
# Import nn.functional
import torch.nn.functional as F
# Define loss function
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(13258.5732, grad_fn=<MseLossBackward>)


In [23]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred, yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(model(inputs), targets))
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)

Training loss:  tensor(28.0312, grad_fn=<MseLossBackward>)


In [24]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.9504,  71.8897],
        [ 83.0699,  99.8204],
        [113.8017, 132.6930],
        [ 31.4002,  45.6542],
        [ 97.4185, 112.6101],
        [ 58.9504,  71.8897],
        [ 83.0699,  99.8204],
        [113.8017, 132.6930],
        [ 31.4002,  45.6542],
        [ 97.4185, 112.6101],
        [ 58.9504,  71.8897],
        [ 83.0699,  99.8204],
        [113.8017, 132.6930],
        [ 31.4002,  45.6542],
        [ 97.4185, 112.6101]], grad_fn=<AddmmBackward>)

In [25]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [26]:
class SimpleNet(nn.Module):
    # Initialize the layers
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(3, 3)
        self.act1 = nn.ReLU() # Activation function
        self.linear2 = nn.Linear(3, 2)
    
    # Perform the computation
    def forward(self, x):
        x = self.linear1(x)
        x = self.act1(x)
        x = self.linear2(x)
        return x
        
model = SimpleNet()
opt = torch.optim.SGD(model.parameters(), 1e-5)
loss_fn = F.mse_loss

In [27]:
fit(100, model, loss_fn, opt)

Training loss:  tensor(35.2617, grad_fn=<MseLossBackward>)
